export const header: string;
export const nav: string;
export const requestDataContainer: string;
export const title: string;
export const method: string;
export const address: string;
export const payload: string;
export const headers: string;
export const go: string;
